# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'TestMainProject.xcworkspace'              #指定workspace
inhibit_all_warnings!        #忽略警告
use_frameworks!

def commpod                     #宏定义几个target都要用的的pod
    pod 'MJRefresh'            #下拉刷新
    pod 'Alamofire', '~> 4.0'  #网络请求
    pod 'SnapKit', '~> 4.0.0'   #autolayout
    pod 'ObjectMapper', '~> 3.1'   #json 转模型
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'BlocksKit'            #将delegate转换为block的库
end


target 'TestMainProject' do
    project 'TestMainProject'
    commpod
    pod 'IQKeyboardManagerSwift' #使用iQ键盘
    pod 'SDWebImage'           #图片离线缓存类
    pod 'AWSS3', '~> 2.6.0'    #AWSS3上传下载
    pod 'IQActionSheetPickerView', '~>2.0.0'  #picker选择器
end


target 'TestMainSDK' do
    project 'TestMainSDK/TestMainSDK'
    commpod
end
